name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Replace environment variables
      run: |
        # Replace placeholders with actual secrets
        find . -name "*.html" -type f -exec sed -i "s/{{AIRTABLE_API_KEY}}/${{ secrets.AIRTABLE_API_KEY }}/g" {} \;
        find . -name "*.html" -type f -exec sed -i "s/{{AIRTABLE_BASE_ID}}/${{ secrets.AIRTABLE_BASE_ID }}/g" {} \;
        find . -name "*.html" -type f -exec sed -i "s/{{AIRTABLE_TABLE_NAME}}/${{ secrets.AIRTABLE_TABLE_NAME }}/g" {} \;
        find . -name "*.html" -type f -exec sed -i "s/{{EMAILJS_SERVICE_ID}}/${{ secrets.EMAILJS_SERVICE_ID }}/g" {} \;
        find . -name "*.html" -type f -exec sed -i "s/{{EMAILJS_TEMPLATE_ID}}/${{ secrets.EMAILJS_TEMPLATE_ID }}/g" {} \;
        find . -name "*.html" -type f -exec sed -i "s/{{EMAILJS_PUBLIC_KEY}}/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" {} \;
        
        # Debug: Show what files were processed
        find . -name "*.html" -type f
        
        # Debug: Show a snippet of the processed file
        echo "=== Sample of processed HTML ==="
        head -20 ./merch.html || head -20 ./*.html
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4